version: '3.8'
services:
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
      - ./:/app
    # aguarda o app ficar disponível e executa os testes; grava relatórios nas pastas montadas
    command: npm run pageObjects-chrome